{% set name = "nested-lookup" %}
{% set version = "0.2.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e39adacd11e879dd6383b0a832cde97edce25d2a29cbc03a9c80fefa3a131e8b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - six

test:
  imports:
    - nested_lookup

about:
  home: https://github.com/russellballestrini/nested-lookup
  # NOTE : The author of nested-lookup releases the code to the public domain,
  # so the source is licensed as MIT for the purposes of use in Conda Forge.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python functions for working with deeply nested documents (lists and dicts)
  dev_url: https://github.com/russellballestrini/nested-lookup

extra:
  recipe-maintainers:
    - moorepants
